events_task/lib/my_app_web/router.ex
defmodule MyAppWeb.Router do
  use MyAppWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)

    plug(Guardian.Plug.Pipeline,
      module: MyAppWeb.Guardian,
      error_handler: MyAppWeb.AuthController
    )

    plug(Guardian.Plug.VerifySession)
    plug(Guardian.Plug.LoadResource, allow_blank: true)
  end

  scope "/", MyAppWeb do
    pipe_through(:browser)
    resources("/events", EventController)
    post("/confirmations", ConfirmationController, :create)
    get("/", PageController, :index)
    post("/update", AuthController, :update)
    get("/login", AuthController, :new)
    get("/logout", AuthController, :destroy)
    post("/login", AuthController, :create)
    get("/login/:magic_token", AuthController, :callback)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/" do
    pipe_through(:api)

    forward("/api", Absinthe.Plug.GraphiQL,
      schema: MyAppWeb.Schema,
      interface: :simple,
      context: %{pubsub: MyAppWeb.Endpoint}
    )
  end
end

events_task/lib/my_app_web/templates/page/index.html.eex
<section>
    <%= if @current_user do %>
    <p class="lead">User: <code>
            <%= @current_user.email %></code>. </p>
    <ui>
        <div id="zatemnenie">
            <div id="okno">
                Edit Menu
                <%= form_for @changeset, auth_path(@conn, :update), fn f -> %>
                <%= label f, :email %><br>
                <%= text_input f, :email,style: "width:100%; text-align: center;" %>
                <%= error_tag f, :email %>
                <br>
                <br>
                    <%= submit "Save",class: "btn btn-sm btn-primary" %>
                <% end %>
            </div>
        </div>
        <a href="#zatemnenie" class="btn btn-lg btn-primary">Edit User</a>
        <td>
            <%= link "New Event", to: event_path(@conn, :new), class: "btn btn-lg btn-primary" %>
        </td>
        <td>
            <%= link "Logout", to: auth_path(@conn, :destroy), class: "btn btn-lg btn-primary" %>
        <td>
    </ui>
    <% else %>
    <h1 class="page-header">Unauthenticated</h1>
    <p class="lead">You are not signed in.</p>
    <%= link "Login", to: auth_path(@conn, :new), class: "btn btn-lg btn-primary" %>
    <% end %>
</section>
<h1 class="page-header">Event list</h1>
<table border="1">
    <th style="text-align: center;">Description</th>
    <th style="text-align: center;">Timestamp </th>
    <th style="text-align: center;">Actions </th>
    <%= if @current_user do %>
    <th style="text-align: center;">Confirmation </th>
    <% end %>
    <%= for event <- @events do %>
    <tr>
        <td>
            <%= event.description %>
        </td>
        <td>
            <%= event.timestamp %>
        </td>
        <td style="text-align: center;">
            <%= link " Show ", to: event_path(@conn, :show, event) %>
            <%= if @current_user do %>
            <%= if @current_user.id == event.user_id do %>
            |
            <%= link " Edit ", to: event_path(@conn, :edit, event) %>
            <% end %>
        </td>
        <td style="text-align: center;">
            <%= if Enum.member?(@current_user_confirmations, event.id) do %>
            Confirmed
            <% else %>
            <%= form_for @conn, confirmation_path(@conn,:create,%{"user_id"=>@current_user.id, "event_id"=>event.id}), [method: :post], fn f -> %>
                    <%= submit "Save" %>
            <% end %>
            <% end %>
            <% end %>
        </td>
    </tr>
    <% end %>
</table>